/**
 * [INPUT]: Pure module — no I/O. The cli `install` command supplies the bun path, the
 *          cli.ts path, PATH entries, and a writability probe.
 * [OUTPUT]: Exports shellQuote, renderLauncher, chooseInstallDir, InstallDirChoice.
 * [POS]: Pillar A5 — the zero-setup launcher. `browse install` drops a tiny launcher on
 *        PATH so a STATELESS shell (Cursor runs each command in a fresh shell) can call
 *        `browse goto ...` with no per-command `export PATH/NC` + `nc()` block. In the
 *        Cursor-course session that boilerplate was re-typed 23 times. Logic kept pure
 *        here so dir-selection and script-rendering are testable without touching disk.
 */

// ─── Shell quoting ─────────────────────────────────────────

/** POSIX single-quote a path so spaces/quotes in it survive in the launcher. */
export function shellQuote(s: string): string {
  return `'${s.replace(/'/g, "'\\''")}'`;
}

// ─── Launcher script ───────────────────────────────────────

/**
 * The launcher body: exec bun on cli.ts, forwarding every arg. A sane default for
 * BROWSE_IGNORE_HTTPS_ERRORS is set but stays overridable by the caller's env.
 */
export function renderLauncher(bunPath: string, cliPath: string): string {
  return [
    '#!/bin/sh',
    '# nightCrawl launcher — generated by `browse install`. Zero per-call setup:',
    '# a fresh shell can run `browse goto ...` with no PATH/NC export block.',
    ': "${BROWSE_IGNORE_HTTPS_ERRORS:=1}"; export BROWSE_IGNORE_HTTPS_ERRORS',
    `exec ${shellQuote(bunPath)} run ${shellQuote(cliPath)} "$@"`,
    '',
  ].join('\n');
}

// ─── Install directory selection ───────────────────────────

export interface InstallDirChoice {
  dir: string;
  onPath: boolean; // true → the launcher is callable immediately; false → caller adds dir to PATH
}

/**
 * Pick where to write the launcher. Prefer a candidate that is BOTH on PATH and
 * writable (callable with zero further setup); else the first writable candidate
 * (off PATH — the caller is told to add it); else the dedicated fallback dir.
 */
export function chooseInstallDir(
  pathEntries: string[],
  candidates: string[],
  fallback: string,
  isWritable: (dir: string) => boolean,
): InstallDirChoice {
  const onPath = new Set(pathEntries);
  for (const c of candidates) if (onPath.has(c) && isWritable(c)) return { dir: c, onPath: true };
  for (const c of candidates) if (isWritable(c)) return { dir: c, onPath: false };
  return { dir: fallback, onPath: onPath.has(fallback) };
}
